// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DiolVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDiolVSIXPackageString = "d85dc7d0-f6c3-4609-9b85-f9783d51c5e5";
        public static Guid guidDiolVSIXPackage = new Guid(guidDiolVSIXPackageString);

        public const string guidDiolVSIXPackageCmdSetString = "2ea0aec1-d51a-4d4e-ae46-49c68767b8b1";
        public static Guid guidDiolVSIXPackageCmdSet = new Guid(guidDiolVSIXPackageCmdSetString);

        public const string guidImagesString = "2dd12e27-238f-42f5-8abd-57280d31d00f";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DiolToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}