name: main_build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'source/**'

env:
  SOLUTION_PATH: source/Diol/Diol.sln

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild /t:restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" ${{ env.SOLUTION_PATH }}