name: main_build

on:
  pull_request:
    branches: [ main ]

env:
  SOLUTION_PATH: source/Diol
  TEST_PROJECT_PATH: tests/unit/Diol.Tests.Units/bin/Release/net48/Diol.Tests.Units.dll

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild /t:restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" ${{ env.SOLUTION_PATH }}/Diol.sln
    
    - name: Setup VS Test Host
      uses: warrenbuckley/Setup-VS-Test-Host@v1

    - name: Run Unit Tests
      run: |
        Get-ChildItem -Recurse -Filter Diol.Tests.Units.dll -Path source/Diol/tests/unit/Diol.Tests.Units/bin | ForEach-Object {
          & "vstest.console.exe" $_.FullName
        }
      shell: pwsh
